version: '3.4'

services:
  app:
    &app
    build: .
    entrypoint: 'entrypoint.sh'
    command: [ 'rails', 's', '-p', '3000', '-b', '0.0.0.0' ]
    environment:
      - RAILS_ENV=development
      - RAILS_LOG_LEVEL=debug
      - DATABASE_USER=avalon
      - DATABASE_PASSWORD=avalon
      - DATABASE_NAME=avalon_development
      - DATABASE_HOST=db
      - FEDORA_URL=http://fcrepo:8080/rest
      - FEDORA_BASE_PATH=/dev
      - SOLR_URL=http://solr:8983/solr/avalon
      - SOLR_HOST=solr
      - SOLR_PORT=8983
      - REDIS_SERVER=redis:6379
      - SETTINGS__REDIS__HOST=redis
      - SETTINGS__REDIS__PORT=6379
      - SETTINGS__REDIS__DB=0
      - DROPBOX_PATH=/var/avalon/dropbox
      - DROPBOX_UPLOAD_URI=/dropbox
      - ENCODE_WORK_DIR=/streams/
      - SECRET_KEY_BASE=abcd1234
      - DEVISE_STRATEGY=database
      - SAML_ASSERTION_CONSUMER_SERVICE_URL=http://av-test.lib.uh.edu:3000/users/saml/auth
      - SAML_ASSERTION_CONSUMER_SERVICE_BINDING=urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
      - SAML_NAME_IDENTIFIER_FORMAT=urn:oasis:names:tc:SAML:2.0:nameid-format:transient
      - SAML_SP_ENTITY_ID=http://av-test.lib.uh.edu:3000/users/saml/metadata
      - SAML_AUTHN_CONTEXT=urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport
      - SAML_SECURITY_ASSERTIONS_ENCRYPTED=false   
      - SAML_IDP_SSO_SERVICE_URL=https://shibboleth.lib.uh.edu/idp/profile/SAML2/Redirect/SSO
      - SAML_IDP_SLO_SERVICE_URL=https://shibboleth.lib.uh.edu/idp/profile/Logout
      - SAML_IDP_CERT=
          -----BEGIN CERTIFICATE-----
          MIIDPzCCAiegAwIBAgIULlNaR/yPtpIHLsg043vHlyUUb9owDQYJKoZIhvcNAQEF
          BQAwIDEeMBwGA1UEAxMVc2hpYmJvbGV0aC5saWIudWguZWR1MB4XDTA5MTEwNjIx
          NTEwOVoXDTI5MTEwNjIxNTEwOVowIDEeMBwGA1UEAxMVc2hpYmJvbGV0aC5saWIu
          dWguZWR1MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiLfH0IINKgkb
          rIOkA/VFCgs+O8Voj/ywl8krAdq2+F5VQQC1+pHoTtcMp7MRHJ/HsRmDjQVkWlNR
          QEnFhnJv38dEIZnfkKWoijqWXTvkQeSvw+9rhU44I1GoBAxYRLm8BuljkOUlt/Xe
          pfusfkjNZaSoeXyS4Q8VGxOtY4FrRXK5SuVhU8tYiBHj+oN7EEHaaj6amADey8u/
          kmGdlJIaq71qwkm9xPeOCcAceLJF0pJBsGUx4sDR4E3y+wGEoPfMSMgJFDH1cmmj
          lFlbE81f6R+57NaX5gIX2oDQStj/D4B5BTSkV0EJiG6ZwcdzsX4nRv+qI1XtMfN3
          vYu8DcA4VwIDAQABo3EwbzBOBgNVHREERzBFghVzaGliYm9sZXRoLmxpYi51aC5l
          ZHWGLGh0dHBzOi8vc2hpYmJvbGV0aC5saWIudWguZWR1L2lkcC9zaGliYm9sZXRo
          MB0GA1UdDgQWBBTWtN42GnjSk3RkyD9wChaumT6JeTANBgkqhkiG9w0BAQUFAAOC
          AQEAckRFXo/Ps3CGTexk0U6VhZ3nUihG8dQR6yECjxpnrZU19u8u8jETLvTdgccL
          LTUlW9oapCGLiDNe9pAz04OrXrWFPaAG64eeFudF9ADat26Fb93alIUlJYTvIH9C
          7cIVqjtE4w1YDiGxIkmlxPCFsjxqQjRNzWvNmJAZ/7BqunjcKu573Ilv4CcteD2P
          E9I51v3x2TJs8SbOPJN87OyKEAilTSERUgXLxPKpGdL/3D3fZTB2cg35/EbDsAHd
          YBqltouvVCvEIi4TGm2qwqj8+X+JwbZ+ZHyLsy6u0GTBDQtMAvij6n17rKlM7DOv
          asKcVxzFt1IOY7qRu811/rvH7A==
          -----END CERTIFICATE-----
      
    ports:
      - 3000:3000
    depends_on:
      - db
      - fcrepo
      - solr
      - nginx
      - redis
    volumes:
      - .:/avalon-app
      - ./dropbox:/var/avalon/dropbox
      - streams:/streams
      - uploads:/var/avalon/uploads

  worker:
    <<: *app
    command: [ 'sidekiq', '-C', 'config/sidekiq.yml' ]
    ports: []

  db:
    image: mysql:8.0
    restart: always
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password'
    environment:
      - MYSQL_USER=avalon
      - MYSQL_PASSWORD=avalon
      - MYSQL_DATABASE=avalon_development
      - MYSQL_ROOT_PASSWORD=my-secret-password
    volumes:
      - db:/var/lib/mysql

  nginx:
    image: nytimes/nginx-vod-module
    restart: always
    ports:
      - 8181:8181
    volumes:
      - ./.nginx.conf:/usr/local/nginx/conf/nginx.conf
      - streams:/usr/local/nginx/streams

  fcrepo:
    image: ghcr.io/samvera/fcrepo4:4.7.5
    restart: always
    environment:
      - JAVA_OPTIONS=-Dfcrepo.log=DEBUG
    volumes:
      - fcrepo:/data:cached
    depends_on:
      - db

  redis:
    image: redis:5-alpine
    restart: always
    volumes:
      - redis:/data

  solr:
    image: solr:6.6.4
    restart: always
    volumes:
      - ./solr/config:/opt/solr/avalon_conf
      - solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - avalon
      - /opt/solr/avalon_conf

volumes:
  db:
  streams:
  uploads:
  redis:
  fcrepo:
  solr:
