version: '3.4'

services:
  app:
    &app
    build: .
    entrypoint: 'entrypoint.sh'
    command: [ 'rails', 's', '-p', '3000', '-b', '0.0.0.0' ]
    env_file:
      - '.env-development'
    environment:
      - RAILS_ENV=development
      - DATABASE_USER=avalon
      - DATABASE_PASSWORD=avalon
      - DATABASE_NAME=avalon_development
      - DATABASE_HOST=db
      - FEDORA_URL=http://fcrepo:8080/rest
      - FEDORA_BASE_PATH=/dev
      - SOLR_URL=http://solr:8983/solr/avalon
      - SOLR_HOST=solr
      - SOLR_PORT=8983
      - REDIS_SERVER=redis:6379
      - SETTINGS__REDIS__HOST=redis
      - SETTINGS__REDIS__PORT=6379
      - DROPBOX_PATH=/var/avalon/dropbox
      - DROPBOX_UPLOAD_URI=/dropbox
      - ENCODE_WORK_DIR=/var/avalon/uploads
      - SECRET_KEY_BASE=abcd1234
    ports:
      - 3000:3000
    depends_on:
      - db
      - fcrepo
      - solr
      - nginx
      - redis
    volumes:
      - .:/avalon-app
      - ./dropbox:/var/avalon/dropbox
      - streams:/streams
      - uploads:/var/avalon/uploads
      - working:/var/avalon/working

  worker:
    <<: *app
    command: [ 'sidekiq', '-C', 'config/sidekiq.yml' ]
    ports: []

  db:
    image: mysql:8.0
    restart: always
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password'
    environment:
      - MYSQL_USER=avalon
      - MYSQL_PASSWORD=avalon
      - MYSQL_DATABASE=avalon_development
      - MYSQL_ROOT_PASSWORD=my-secret-password
    volumes:
      - db:/var/lib/mysql

  nginx:
    image: nytimes/nginx-vod-module
    restart: always
    ports:
      - 8181:8181
    volumes:
      - ./.nginx.conf:/usr/local/nginx/conf/nginx.conf
      - streams:/usr/local/nginx/streams

  fcrepo:
    image: ghcr.io/samvera/fcrepo4:4.7.5
    restart: always
    volumes:
      - fcrepo:/data:cached
    depends_on:
      - db

  redis:
    image: redis:5-alpine
    restart: always
    volumes:
      - redis:/data

  solr:
    image: solr:6.6.4
    restart: always
    volumes:
      - ./solr/config:/opt/solr/avalon_conf
      - solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - avalon
      - /opt/solr/avalon_conf

volumes:
  db:
  streams:
  uploads:
  working:
  redis:
  fcrepo:
  solr:
