version: '3'

services:
  app:
    build: .
    entrypoint: 'docker-entrypoint.sh'
    command: ['rails', 's', '-p', '3000', '-b', '0.0.0.0']
    env_file: 
      - '.env'
      - '.env-development'
    ports:
      - 3000:3000
    depends_on: 
      - db
      - fcrepo
      - memcached
      - solr
      - matterhorn
      - nginx
      - redis
    volumes:
      - .:/avalon-app
      - ./dropbox:/var/avalon/dropbox
      - streams:/streams
      - uploads:/var/avalon/uploads

  db:
    image: mysql:5.7
    restart: always
    env_file: '.env-db'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - db:/var/lib/mysql

  memcached:
    image: bitnami/memcached

  matterhorn:
    image: seanlw/matterhorn
    restart: always
    ports:
      - 8080:8080
    volumes: 
      - ./dropbox:/var/avalon/dropbox
      - uploads:/var/avalon/uploads
      - streams:/streams

  nginx:
    image: nytimes/nginx-vod-module
    restart: always
    ports:
      - 8181:8181
    volumes:
      - ./.nginx.conf:/usr/local/nginx/conf/nginx.conf
      - streams:/usr/local/nginx/streams

  fcrepo:
    image: ghcr.io/samvera/fcrepo4:4.7.5
    restart: always
    volumes:
      - fcrepo:/data:cached

  redis:
    image: redis:5-alpine
    restart: always
    volumes:
      - redis:/data

  solr:
    image: solr:6.6
    restart: always
    volumes:
      - solr:/opt/solr/server/solr

volumes:
  db:
  streams:
  uploads:
  redis:
  fcrepo:
  solr: