domain:
  host: localhost
  port: 3000
  protocol: http
streaming:
  server: :nginx
  stream_token_ttl: 20 #minutes
  content_path: /streams/
  rtmp_base: "rtmp://localhost/avalon"
  http_base: "http://localhost:8181/hls"
  default_quality: "low"
timeliner:
  timeliner_url: "http://localhost:3000/timeliner"
encoding:
  engine_adapter: ffmpeg
  presets_path: config/ffmpeg_presets.yml
  working_file_path: "/streams/"
initial_user: slwatkins@uh.edu
mediainfo:
  path: "/usr/bin/mediainfo"
ffmpeg:
  path: "/usr/bin/ffmpeg"
master_file_management:
  strategy: "delete"
